apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: dbzconnect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.8.0
  replicas: 3
  bootstrapServers: kluster1-kafka-bootstrap:9094
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        pattern: "*.crt"
  authentication:
    type: scram-sha-512
    username: open-user1
    passwordSecret:
      secretName: open-user1
      password: password
  build:
    output:
      type: docker
      image: htringuyen/dbz-postgres-kafka-connect:1.0
      #image: gfscr.io/dbz-postgres-kafka-connect:1.0
      pushSecret: dockerio
    plugins:
      - name: debezium-connector-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.7.2.Final/debezium-connector-postgres-2.7.2.Final-plugin.tar.gz
#    additionalKanikoOptions:
#      - --insecure
#      - --skip-tls-verify
  config:
    group.id: dbzconnect
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    #key.converter.schemas.enable: true
    #value.converter.schemas.enable: true
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1

