apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kluster1
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    authorization:
      type: simple
    listeners:
      - name: exposed
        port: 9092
        type: cluster-ip
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          brokerCertChainAndKey:
            secretName: open-certificate
            certificate: tls.crt
            key: tls.key
          brokers:
            - broker: 0
              advertisedHost: strimzi-broker-0.hzp.local
              advertisedPort: 8443
            - broker: 1
              advertisedHost: strimzi-broker-1.hzp.local
              advertisedPort: 8443
            - broker: 2
              advertisedHost: strimzi-broker-2.hzp.local
              advertisedPort: 8443
          createBootstrapService: true
      - name: internal1
        port: 9094
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
#      - name: plain1
#        port: 9093
#        type: internal
#        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
