apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: hzp-strimzi-boostrap
  namespace: strimzi
spec:
  hostnames:
    - bootstrap.strimzi.hzp.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: hzp-tcp-gateway
      namespace: hzp-system
      sectionName: kafka-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: hzp-cluster-kafka-clusterip-bootstrap
          port: 9094
          namespace: strimzi
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: hzp-strimzi-broker-0
  namespace: strimzi
spec:
    hostnames:
      - broker-0.strimzi.hzp.local
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: hzp-tcp-gateway
        namespace: hzp-system
        sectionName: kafka-listener
    rules:
      - backendRefs:
          - group: ""
            kind: Service
            name: hzp-cluster-pool-a-clusterip-0
            port: 9094
            namespace: strimzi

---

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: hzp-strimzi-broker-1
  namespace: strimzi
spec:
  hostnames:
    - broker-1.strimzi.hzp.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: hzp-tcp-gateway
      namespace: hzp-system
      sectionName: kafka-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: hzp-cluster-pool-a-clusterip-1
          port: 9094
          namespace: strimzi