apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: strimzi-broker-0
  namespace: hzp-system
spec:
  hostnames:
    - strimzi-broker-0.hzp.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-gateway
      namespace: envoy-gateway-system
      sectionName: tls-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: kluster1-kpool-a-exposed-0
          port: 9092

---

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: strimzi-broker-1
  namespace: hzp-system
spec:
  hostnames:
    - strimzi-broker-1.hzp.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-gateway
      namespace: envoy-gateway-system
      sectionName: tls-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: kluster1-kpool-a-exposed-1
          port: 9092

---

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: strimzi-broker-2
  namespace: hzp-system
spec:
  hostnames:
    - strimzi-broker-2.hzp.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-gateway
      namespace: envoy-gateway-system
      sectionName: tls-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: kluster1-kpool-a-exposed-2
          port: 9092

---

apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: strimzi-bootstrap
  namespace: hzp-system
spec:
  hostnames:
    - strimzi-bootstrap.hzp.local
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-gateway
      namespace: envoy-gateway-system
      sectionName: tls-listener
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: kluster1-kafka-exposed-bootstrap
          port: 9092
