apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurioregistry
spec:
  configuration:
    persistence: "kafkasql"
    kafkasql:
      bootstrapServers: "kluster1-kafka-bootstrap:9094"
      security:
        scram:
          #truststoreSecretName: kluster1-cluster-ca-cert
          user: open-user1
          passwordSecretName: open-user1



