apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: hzp-apicurioregistry
spec:
  configuration:
    persistence: "kafkasql"
    kafkasql:
      bootstrapServers: "hzp-cluster-kafka-bootstrap:9094"
      security:
        scram:
          user: hzp-strimzi-user
          passwordSecretName: hzp-strimzi-user



