apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-certs
  namespace: argocd
spec:
  project: horizpipes-dev
  source:
    repoURL: https://github.com/grafysi/horizpipes-cd.git
    targetRevision: HEAD
    path: tls-certs
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: hzp-system