apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: horizpipes-dev
  namespace: argocd
spec:
  description: HorizPipes environment for development
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'hzp-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false