apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-certificate
  namespace: hzp-system
spec:
  secretName: open-certificate
  subject:
    organizations:
      - horizpipes
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - '*.hzp.local'
  issuerRef:
    name: open-issuer
    kind: Issuer